# Generated by Django 4.1.6 on 2023-02-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
