# Generated by Django 4.1.7 on 2023-02-20 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0003_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='voters',
        ),
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voted',
        ),
    ]
